module.exports = {
    USER_INFO_NEW: 'USER_INFO_NEW',
    USER_INFO_UPDATE: 'USER_INFO_UPDATE',
    USER_NEW: 'USER_NEW',
    USER_HAS_LEFT: 'USER_HAS_LEFT',

    // making call
    INCOMING_CALL: 'INCOMING_CALL',
    MAKE_CALL: 'MAKE_CALL',

    // webrtc related events
    ICE_CANDIDATE: 'ICE_CANDIDATE',
    SEND_ICE_CANDIDATE: 'SEND_ICE_CANDIDATE',
    CREATE_OFFER: 'CREATE_OFFER',
    ON_OFFER: 'ON_OFFER',
    CREATE_ANSWER: 'CREATE_ANSWER',
    ON_ANSWER: 'ON_ANSWER'
}