module.exports = {
    USER_INFO_NEW: 'USER_INFO_NEW',
    USER_INFO_UPDATE: 'USER_INFO_UPDATE',
    USER_NEW: 'USER_NEW',
    OUT_USER_HAS_LEFT: 'USER_HAS_LEFT',

    //
    OUT_USER_ID: 'USER_ID',
    OUT_USERS_LIST: 'USERS_LIST',

    // making call
    OUT_INCOMING_CALL: 'INCOMING_CALL',
    IN_OUT_END_CALL: 'END_CALL',
    IN_MAKE_CALL: 'MAKE_CALL',

    // webrtc related events
    ICE_CANDIDATE: 'ICE_CANDIDATE',
    SEND_ICE_CANDIDATE: 'SEND_ICE_CANDIDATE',
    CREATE_OFFER: 'CREATE_OFFER',
    ON_OFFER: 'ON_OFFER',
    CREATE_ANSWER: 'CREATE_ANSWER',
    ON_ANSWER: 'ON_ANSWER'
}